insert into bank (name) values ('AFIRME');
insert into bank (name) values ('BAJIO');
insert into bank (name) values ('Banamex');
insert into bank (name) values ('Banca Mifel');
insert into bank (name) values ('BANCO AUTOFIN MÉXICO');
insert into bank (name) values ('BANCO AZTECA ');
insert into bank (name) values ('Banco Bansefi');
insert into bank (name) values ('BANCO WALMART ADELANTE');
insert into bank (name) values ('BANCOMER');
insert into bank (name) values ('Banjercito');
insert into bank (name) values ('BANORTE');
insert into bank (name) values ('BanRegio');
insert into bank (name) values ('BANSI');
insert into bank (name) values ('CREDOMATICO DE MEXICO S.A DE C.V. ');
insert into bank (name) values ('Hsbc');
insert into bank (name) values ('Inbursa');
insert into bank (name) values ('INBURSA S.A.');
insert into bank (name) values ('Interacciones');
insert into bank (name) values ('Invex');
insert into bank (name) values ('Ixe');
insert into bank (name) values ('PROSA');
insert into bank (name) values ('PROSA BANCA AFIRME');
insert into bank (name) values ('Prosa Banco Afirme');
insert into bank (name) values ('Prosa Banco Fácil S.A.');
insert into bank (name) values ('Prosa Credomatic México');
insert into bank (name) values ('PROSA SPIRA MÉXICO SA DE CV');
insert into bank (name) values ('Santander Serfin');
insert into bank (name) values ('Scotiabank Inverlat');

insert into bin (bin, credit_card_type_id, name, issuer_id)values ('448790',(SELECT id FROM credit_card_type where name = 'VISA'),'AFIRME VISA ORO',(SELECT id from bank where name = 'AFIRME'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512048',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'AFIRME MASTERCARD CLÁSICA',(SELECT id from bank where name = 'AFIRME'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('420199',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA DE CREDITO BAJIO',(SELECT id from bank where name = 'BAJIO'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('403703',(SELECT id FROM credit_card_type where name = 'VISA'),'OMNILIFE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('403707',(SELECT id FROM credit_card_type where name = 'VISA'),'CONTINENTAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('405306',(SELECT id FROM credit_card_type where name = 'VISA'),'AFFINITY CARD',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('405930',(SELECT id FROM credit_card_type where name = 'VISA'),'CUENTA PERFILES',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('407458',(SELECT id FROM credit_card_type where name = 'VISA'),'Corporativa',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('407559',(SELECT id FROM credit_card_type where name = 'VISA'),'S Bussines',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('410852',(SELECT id FROM credit_card_type where name = 'VISA'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('420713',(SELECT id FROM credit_card_type where name = 'VISA'),'CITIBANK AADVANTAGE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('435741',(SELECT id FROM credit_card_type where name = 'VISA'),'GENERAL MOTORS',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('439120',(SELECT id FROM credit_card_type where name = 'VISA'),'INFINITE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441541',(SELECT id FROM credit_card_type where name = 'VISA'),'D Super',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441545',(SELECT id FROM credit_card_type where name = 'VISA'),'CTA MAESTRA VISA CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441549',(SELECT id FROM credit_card_type where name = 'VISA'),'CTA MTRA VISA ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('451331',(SELECT id FROM credit_card_type where name = 'VISA'),'AHORRO JUVENIL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('451332',(SELECT id FROM credit_card_type where name = 'VISA'),'AHORRO CRECIENTE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('451333',(SELECT id FROM credit_card_type where name = 'VISA'),'SOLUCION EFECTIVA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('454057',(SELECT id FROM credit_card_type where name = 'VISA'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('454069',(SELECT id FROM credit_card_type where name = 'VISA'),'CLASICA.',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('454492',(SELECT id FROM credit_card_type where name = 'VISA'),'PATRIMONIAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455255',(SELECT id FROM credit_card_type where name = 'VISA'),'ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('479461',(SELECT id FROM credit_card_type where name = 'VISA'),'CHEDRAUI',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('480790',(SELECT id FROM credit_card_type where name = 'VISA'),'Respt Indiv',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('485942',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA COMPRAS',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('485943',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA DE DISTRIBUCION',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('490176',(SELECT id FROM credit_card_type where name = 'VISA'),'AFINIDAD CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('490178',(SELECT id FROM credit_card_type where name = 'VISA'),'AFINIDAD ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491271',(SELECT id FROM credit_card_type where name = 'VISA'),'Travel Pas',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491272',(SELECT id FROM credit_card_type where name = 'VISA'),'Travel Pas Elite Elevel',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491501',(SELECT id FROM credit_card_type where name = 'VISA'),'ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491502',(SELECT id FROM credit_card_type where name = 'VISA'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493164',(SELECT id FROM credit_card_type where name = 'VISA'),'AFINIDAD CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493165',(SELECT id FROM credit_card_type where name = 'VISA'),'AFINIDAD ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('494388',(SELECT id FROM credit_card_type where name = 'VISA'),'CORPORATIVA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('498460',(SELECT id FROM credit_card_type where name = 'VISA'),'SOCIO FUNDADOR',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('504563',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'INVERMATICO AFINIDAD MAESRO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512709',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Chivas',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512795',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Tarjeta de Servicio',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512809',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Cruz Azul',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512823',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Pumas',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('517712',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PAGOMATICO INTERNACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('517721',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'DEBITO INTERNACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('517771',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'INVERMATICO ESTADOS INTERNACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('517795',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'INVERMATICO INTERNACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('518004',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'OFFICE DEPOT COMPARTIDA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('518851',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'TRAVEL PASS MC',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('518853',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'TELETON',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('518899',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'FRECUENTA ORO (Travel Pass Elite)',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('520213',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CLASICA GRADUADOS',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('520416',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CUENTA PERFILES',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('520608',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CREDITO FAMILIAR',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('520694',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CTA MTRA DORADA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('520698',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CTA MTRA CLASIC',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('522130',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'COLEGGE CARD (B`Smart Colegge)',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('524711',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PERFIL UNIVERSITARIO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('525424',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CITIBANK AADVANTAGE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('525678',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'TARJETA MAX',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('526489',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'América',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528804',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'AFINIDAD CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528805',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PRICE SMART',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528843',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528851',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'FRECUENTA ORO (Travel Pass)',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528866',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Club América',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528875',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BINACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('528877',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'GIGANTE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('529001',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('529088',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'AFINIDAD CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('529091',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('529093',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CTA MTRA NACION',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('530056',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Soriana',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('530756',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Comercial Mexicana',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('540533',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'TARJETA COMPRAS',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('542537',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544672',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('545039',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'AADVANTAGE',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547075',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'AFINIDAD CLASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547093',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547112',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'ORO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547370',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CORPORATIVA COMPARTIDA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547380',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CORPORATIVA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547514',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'IMPULSO EMPRESARIAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('548234',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'B SMART',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('549138',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PLATINUM',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('554492',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CUENTA UNO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('554628',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'D ACCESO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('558784',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Resp Indiv',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('559209',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Calimax',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854809',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'PAGOMATICO NACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854819',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'CUENTA BASICA',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854858',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'INVERMATICO ESTADOS',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854859',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'PAGOMATICO NACIONAL',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854897',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'INVERMATICO',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854899',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'Cotsco',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854881',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'Soriana Privada I',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('881006',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'Soriana Pagos Fijos I',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('881052',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'Soriana Pagos Fijos',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('882204',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'Soriana',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('428211',(SELECT id FROM credit_card_type where name = 'VISA'),'Julio Oro',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('520021',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Home Depot',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544925',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Coemitida VIII',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('549631',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Martí­ Premium',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('549639',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Martí­ Clásica',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('554625',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Coemitida V',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('408242',(SELECT id FROM credit_card_type where name = 'VISA'),'ITESM Clásica',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('545631',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Clásica',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('408244',(SELECT id FROM credit_card_type where name = 'VISA'),'Legionarios Oro',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('408245',(SELECT id FROM credit_card_type where name = 'VISA'),'Oro',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491501',(SELECT id FROM credit_card_type where name = 'VISA'),'Oro',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('548236',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Diamond',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('552523',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Professional',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('552526',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Central Travel Account',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('854823',(SELECT id FROM credit_card_type where name = 'BANAMEX'),'Tarjeta de Distribución',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('429522',(SELECT id FROM credit_card_type where name = 'VISA'),'Premia',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('529028',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Premia',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('411111',(SELECT id FROM credit_card_type where name = 'VISA'),'Demo',(SELECT id from bank where name = 'Banamex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('427213',(SELECT id FROM credit_card_type where name = 'VISA'),'Mifel Visa Gold Credit',(SELECT id from bank where name = 'Banca Mifel'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('460766',(SELECT id FROM credit_card_type where name = 'VISA'),'MINITARJETA',(SELECT id from bank where name = 'BANCO AUTOFIN MÉXICO'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('421364',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA AZTECA',(SELECT id from bank where name = 'BANCO AZTECA '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('476202',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA DE CREDITO ORO',(SELECT id from bank where name = 'BANCO AZTECA '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('476203',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA DE CREDITO INFINITE',(SELECT id from bank where name = 'BANCO AZTECA '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('476204',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA DE CREDITO CORPORATIVA',(SELECT id from bank where name = 'BANCO AZTECA '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477831',(SELECT id FROM credit_card_type where name = 'VISA '),'TARJETA DE CREDITO CLASISA',(SELECT id from bank where name = 'BANCO AZTECA '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('639484',(SELECT id FROM credit_card_type where name = 'VISA'),'Canasta Garantizada',(SELECT id from bank where name = 'Banco Bansefi'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('444888',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PREPAGO INTERNACIONAL',(SELECT id from bank where name = 'BANCO WALMART ADELANTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('444889',(SELECT id FROM credit_card_type where name = 'VISA'),'PREPAGO INTERNACIONAL',(SELECT id from bank where name = 'BANCO WALMART ADELANTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('530113',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PREPAGO INTERNACIONAL',(SELECT id from bank where name = 'BANCO WALMART ADELANTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('539975',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'DEBITO INTERNACIONAL AHORRO',(SELECT id from bank where name = 'BANCO WALMART ADELANTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('409851',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Jovenes',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('409852',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Regalo ',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('410180',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Educación',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('410181',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Platinum ',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441310',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441311',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441312',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Express Ahorro',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441313',(SELECT id FROM credit_card_type where name = 'VISA'),'Usuario Express Dispersion ',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('441314',(SELECT id FROM credit_card_type where name = 'VISA'),'Oro Internacional ',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455500',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Clásica',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455503',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455504',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Infinite',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455505',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Oro',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455506',(SELECT id FROM credit_card_type where name = 'Visa'),'Visa Clásica Internacional Empresarial',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455507',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Clásica Internacional Empresarial',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455509',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa si Activa',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455510',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Cuenta Maestra Oro',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455513',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Coporativa',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455514',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Corporativa ',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455515',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Corporativa',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455519',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Gasolina ',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455525',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455526',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455527',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455529',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Patrimonial Oro Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455540',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Oro Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455545',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493160',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493161',(SELECT id FROM credit_card_type where name = 'VISA'),'Clásica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493162',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Oro Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('494398',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Congelada',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('542010',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('542977',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544551',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547077',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547086',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547095',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Oro Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547155',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547156',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Oro Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547492',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MasterCard Empresarial Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('455508',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Instantanea',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477210',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta de crédito IPN',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477211',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Congelada',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477213',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Oro Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477214',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta Platinum Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477291',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta clasica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477292',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta clasica Internacional Rayados',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('477212',(SELECT id FROM credit_card_type where name = 'VISA'),'Clasica Internacional',(SELECT id from bank where name = 'BANCOMER'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491343',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa oro internacional',(SELECT id from bank where name = 'Banjercito'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491346',(SELECT id FROM credit_card_type where name = 'VISA'),'Visa Clasica Internacionala',(SELECT id from bank where name = 'Banjercito'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547080',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Mastercard Standard Internacional ',(SELECT id from bank where name = 'Banjercito'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491341',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE CLASICA VISA INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491366',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE VISA CLASICA NACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491369',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE VISA EMPRESARIAL INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491371',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE VISA ORO INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491375',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE VISA EMPRESARIAL NACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491376',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE VISA EMPRESARIAL INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491586',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA INFINITE BANORTE',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493157',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE ORO VISA INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493172',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE CLASICA VISA INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493173',(SELECT id FROM credit_card_type where name = 'VISA'),'BANORTE ORO VISA INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544548',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE MASTERCARD INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544549',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE MASTERCARD ORO INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544550',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE MASTERCARD NACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547050',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'CREDITO MASTERCARD DE BANORTE',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547078',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE MASTER CARD INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547079',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE MASTERCARD STANDAR INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547096',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE ORO MASTER CARD INTERNAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547097',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BANORTE MASTERCARD ORO INTERNACIONAL',(SELECT id from bank where name = 'BANORTE'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('474175',(SELECT id FROM credit_card_type where name = 'VISA'),'Banregio Clasica Internacional',(SELECT id from bank where name = 'BanRegio'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('435769',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA ELECTRON',(SELECT id from bank where name = 'BANSI'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('439185',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA CLASICA ',(SELECT id from bank where name = 'CREDOMATICO DE MEXICO S.A DE C.V. '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('439186',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA DORADA',(SELECT id from bank where name = 'CREDOMATICO DE MEXICO S.A DE C.V. '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('439187',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA PLATINUM',(SELECT id from bank where name = 'CREDOMATICO DE MEXICO S.A DE C.V. '));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('416502',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL PREMIER',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('421316',(SELECT id FROM credit_card_type where name = 'VISA'),'HSBC VISA CLASICA',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('426513',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA EMPRESARIAL VISA',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('426514',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL TARJETA DE PAGOS FIJOS ABIERTA',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('430967',(SELECT id FROM credit_card_type where name = 'VISA'),'HSBC VISA ELECTRON',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('452421',(SELECT id FROM credit_card_type where name = 'VISA'),'HSBC VISA CLASICA',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('456880',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL VISA CLASICA NACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491089',(SELECT id FROM credit_card_type where name = 'VISA'),'HSBC VISA ELECTRON',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491279',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL BUXX',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491280',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL VISA CLASICA INTERNACIONAL  (ATLANTICO)',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491281',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL VISA ORO INTERNACIONAL      (ATLANTICO)',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491282',(SELECT id FROM credit_card_type where name = 'VISA'),'HSBC VISA CLASICA',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491283',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL VISA ORO INTERNACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491284',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL VISA CLASICA INTERNACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491294',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL CREDITO ORO INTERNACIONAL     (INBURSA)',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491295',(SELECT id FROM credit_card_type where name = 'VISA'),'BITAL CREDITO CLASICA INTERNACIONAL (INBURSA)',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493166',(SELECT id FROM credit_card_type where name = 'VISA'),'PYMES',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('522174',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'HSBC MASTERCARD CLASICA',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('540956',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL MASTERCARD ORO INTERNACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('541278',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL MASTERCARD INTERNACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('541286',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL CLASICA MASTER CARD INTERNACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('541290',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL ORO MASTER CARD INTERNACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547068',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL MASTERCARD NACIONAL',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547074',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL MASTERCARD INTERNACIONAL    (ATLANTICO)',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547092',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'BITAL ORO MASTERCARD INTERNACIONAL(ATLANTICO)',(SELECT id from bank where name = 'Hsbc'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('404360',(SELECT id FROM credit_card_type where name = 'VISA'),'Inbursa Oro',(SELECT id from bank where name = 'Inbursa'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('431479',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta de Crédito Corporativa efe',(SELECT id from bank where name = 'Inbursa'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('465828',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta de Débito efe',(SELECT id from bank where name = 'Inbursa'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('465829',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta de Débito efe',(SELECT id from bank where name = 'Inbursa'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('473701',(SELECT id FROM credit_card_type where name = 'VISA'),'Tarjeta de Crédito efe',(SELECT id from bank where name = 'Inbursa'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('462974',(SELECT id FROM credit_card_type where name = 'VISA'),'INBURSA TELCEL',(SELECT id from bank where name = 'INBURSA S.A.'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('545094',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Interacciones Tarjeta de Débito Maestro Internacional',(SELECT id from bank where name = 'Interacciones'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('601326',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'Interacciones Tarjeta de Débito Maestro Internacional',(SELECT id from bank where name = 'Interacciones'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('421811',(SELECT id FROM credit_card_type where name = 'VISA'),'SPIRA CLASICA',(SELECT id from bank where name = 'Invex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('421812',(SELECT id FROM credit_card_type where name = 'VISA'),'INVEX MARCA COMPARTIDA',(SELECT id from bank where name = 'Invex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('463186',(SELECT id FROM credit_card_type where name = 'VISA'),'SPIRA PLATINUM',(SELECT id from bank where name = 'Invex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('463187',(SELECT id FROM credit_card_type where name = 'VISA'),'SPIRA EMPRESARIAL',(SELECT id from bank where name = 'Invex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('492143',(SELECT id FROM credit_card_type where name = 'VISA'),'SPIRA DEBITO',(SELECT id from bank where name = 'Invex'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('402318',(SELECT id FROM credit_card_type where name = 'VISA'),'IXE VISA INFINITE',(SELECT id from bank where name = 'Ixe'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('425981',(SELECT id FROM credit_card_type where name = 'VISA'),'IXE VISA ORO INTERNACIONAL',(SELECT id from bank where name = 'Ixe'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('425982',(SELECT id FROM credit_card_type where name = 'VISA'),'IXE VISA CLASICA INTERNACIONAL',(SELECT id from bank where name = 'Ixe'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('425984',(SELECT id FROM credit_card_type where name = 'VISA'),'IXE VISA ORO INTERNACIONAL',(SELECT id from bank where name = 'Ixe'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('433454',(SELECT id FROM credit_card_type where name = 'VISA'),'IXE VISA CLASICA INTERNACIONAL',(SELECT id from bank where name = 'Ixe'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512745',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'IXE ORO MASTERCARD',(SELECT id from bank where name = 'Ixe'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('407399',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA ORO INTERNACIONAL',(SELECT id from bank where name = 'PROSA'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('426808',(SELECT id FROM credit_card_type where name = 'VISA'),'MULTIVA DEBITO',(SELECT id from bank where name = 'PROSA'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('512029',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MASTER CARD BLANC',(SELECT id from bank where name = 'PROSA BANCA AFIRME'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('539672',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MASTERCARD ORO',(SELECT id from bank where name = 'Prosa Banco Afirme'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('400605',(SELECT id FROM credit_card_type where name = 'VISA'),'VISA CLASICO INTERNACIONAL',(SELECT id from bank where name = 'Prosa Banco Fácil S.A.'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('517844',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MASTER CARD CLASICA',(SELECT id from bank where name = 'Prosa Credomatic México'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('524385',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MASTER CARD PLATINUM',(SELECT id from bank where name = 'Prosa Credomatic México'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('525797',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'MASTER CARD DORADA',(SELECT id from bank where name = 'Prosa Credomatic México'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('406129',(SELECT id FROM credit_card_type where name = 'VISA'),'AMBAR',(SELECT id from bank where name = 'PROSA SPIRA MÉXICO SA DE CV'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('446130',(SELECT id FROM credit_card_type where name = 'VISA'),'FX',(SELECT id from bank where name = 'PROSA SPIRA MÉXICO SA DE CV'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('446137',(SELECT id FROM credit_card_type where name = 'VISA'),'AVAL CARD',(SELECT id from bank where name = 'PROSA SPIRA MÉXICO SA DE CV'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('446138',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA NISSAN',(SELECT id from bank where name = 'PROSA SPIRA MÉXICO SA DE CV'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('446139',(SELECT id FROM credit_card_type where name = 'VISA'),'TARJETA RENAULT',(SELECT id from bank where name = 'PROSA SPIRA MÉXICO SA DE CV'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('454747',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN EMPRESARIAL VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491327',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN EMPRESARIAL VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491512',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN CLASICA VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491572',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN CLASICA VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491573',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN ORO VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493135',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN CLASICA VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('493136',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN ORO VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('494133',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN CLASICA VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('494134',(SELECT id FROM credit_card_type where name = 'VISA'),'SANTANDER SERFIN ORO VISA',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547146',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN LIGHT MC',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('540845',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN ORO MASTERCARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('545307',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN CLASICA MASTER CARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547015',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN ORO MASTERCARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547046',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN ORO MASTERCARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547157',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN CLASICA MASTER CARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547484',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN EMPRESARIAL MASTERCARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('554900',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN PLATINO MASTERCARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('557905',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SANTANDER SERFIN DEBITO MASTERCARD',(SELECT id from bank where name = 'Santander Serfin'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491871',(SELECT id FROM credit_card_type where name = 'VISA'),'SCOTIABANK VISA CLASICA',(SELECT id from bank where name = 'Scotiabank Inverlat'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491872',(SELECT id FROM credit_card_type where name = 'VISA'),'SCOTIABANK VISA ORO',(SELECT id from bank where name = 'Scotiabank Inverlat'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('491873',(SELECT id FROM credit_card_type where name = 'VISA'),'SCOTIABANK VISA EMPRESARIAL',(SELECT id from bank where name = 'Scotiabank Inverlat'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('544204',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SCOTIABANK MASTERCARD ORO',(SELECT id from bank where name = 'Scotiabank Inverlat'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('545375',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SCOTIABANK MASTERCARD STANDARD',(SELECT id from bank where name = 'Scotiabank Inverlat'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('547407',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'SCOTIABANK MASTERCARD EMPRESARIAL',(SELECT id from bank where name = 'Scotiabank Inverlat'));
insert into bin (bin, credit_card_type_id, name, issuer_id)values ('552263',(SELECT id FROM credit_card_type where name = 'MASTERCARD'),'PLATINUM MASTERCARD',(SELECT id from bank where name = 'Scotiabank Inverlat'));

